-- =============================================================================
-- 08-database-schema.sql — Consolidated PostgreSQL DDL for E-Commerce Platform
-- =============================================================================
-- Database: PostgreSQL 16 (pgvector extension available)
-- Engine:   Single Postgres instance, 5 logical schemas
-- Migrations: Liquibase-managed per service (this file is a READ-ONLY reference)
--
-- Naming conventions:
--   Tables/columns:  snake_case
--   PKs:             id (BIGINT GENERATED BY DEFAULT AS IDENTITY)
--   FKs:             fk_<child>_<parent>
--   Indexes:         idx_<table>_<column>
--   Unique:          uq_<table>_<column>
--   Check:           ck_<table>_<constraint>
--   Timestamps:      created_at, updated_at (TIMESTAMPTZ)
--   Money:           NUMERIC(19, 2)
--
-- NOTE: The orders schema reflects the REAL order-management-api Liquibase
--       changelogs (v1.0/01–08). Do NOT alter without updating the source.
-- =============================================================================

-- =============================================================================
-- SCHEMA: auth  —  Managed by auth-service (port 8081)
-- =============================================================================
-- Managed by Liquibase in auth-service
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE auth.users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    full_name      VARCHAR(255) NOT NULL,
    phone_number   VARCHAR(50),
    role           VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE auth.refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    token        VARCHAR(512) NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES auth.users (id) ON DELETE CASCADE,
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token)
);

CREATE INDEX idx_refresh_tokens_user_id ON auth.refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_token   ON auth.refresh_tokens (token);

-- =============================================================================
-- SCHEMA: cart  —  Managed by cart-service (port 8082)
-- =============================================================================
-- Managed by Liquibase in cart-service
CREATE SCHEMA IF NOT EXISTS cart;

CREATE TABLE cart.carts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_carts_user_id UNIQUE (user_id)
);

CREATE TABLE cart.cart_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     BIGINT        NOT NULL,
    product_id  BIGINT        NOT NULL,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(19,2) NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_cart_items_cart    FOREIGN KEY (cart_id)
        REFERENCES cart.carts (id) ON DELETE CASCADE,
    CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_cart_items_price_non_negative CHECK (unit_price >= 0)
);

CREATE TABLE cart.idempotency_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64)  NOT NULL,
    response_status INTEGER      NOT NULL,
    response_body   TEXT         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_cart_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX idx_cart_items_cart_id    ON cart.cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON cart.cart_items (product_id);
CREATE INDEX idx_carts_user_id         ON cart.carts (user_id);

-- =============================================================================
-- SCHEMA: product  —  Managed by product-service (port 8083)
-- =============================================================================
-- Managed by Liquibase in product-service
CREATE SCHEMA IF NOT EXISTS product;

CREATE TABLE product.products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    description     TEXT,
    price           NUMERIC(19, 2) NOT NULL,
    stock_quantity  INTEGER        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_products_price_non_negative     CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative     CHECK (stock_quantity >= 0)
);

CREATE TABLE product.categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE product.product_categories (
    product_id   BIGINT NOT NULL,
    category_id  BIGINT NOT NULL,
    CONSTRAINT pk_product_categories PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_pc_product  FOREIGN KEY (product_id)
        REFERENCES product.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_pc_category FOREIGN KEY (category_id)
        REFERENCES product.categories (id) ON DELETE RESTRICT
);

CREATE INDEX idx_product_categories_category_id ON product.product_categories (category_id);

-- =============================================================================
-- SCHEMA: orders  —  Managed by order-management-api (port 8084)
-- =============================================================================
-- Managed by Liquibase in order-management-api
-- THIS SCHEMA IS AUTHORITATIVE: columns and constraints match the real
-- Liquibase changelogs at:
--   order-management-api/src/main/resources/db/changelog/v1.0/01–08
-- Do NOT modify without updating the source changelogs first.
CREATE SCHEMA IF NOT EXISTS orders;

-- --- Root entity: customers -----------------------------------------------
CREATE TABLE orders.customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(50),
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64)  NOT NULL DEFAULT 'system',
    updated_by    VARCHAR(64)  NOT NULL DEFAULT 'system',
    CONSTRAINT uq_orders_customers_email UNIQUE (email)
);

-- --- Root entity: products (order-management-api catalog snapshot) ---------
CREATE TABLE orders.products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    description     TEXT,
    price           NUMERIC(19, 2) NOT NULL,
    stock_quantity  INTEGER        NOT NULL DEFAULT 0,
    version         BIGINT         NOT NULL DEFAULT 0,
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(64)    NOT NULL DEFAULT 'system',
    updated_by      VARCHAR(64)    NOT NULL DEFAULT 'system',
    CONSTRAINT ck_orders_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_orders_products_stock_non_negative CHECK (stock_quantity >= 0)
);

-- --- Root entity: categories ----------------------------------------------
CREATE TABLE orders.categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    version      BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(64)  NOT NULL DEFAULT 'system',
    updated_by   VARCHAR(64)  NOT NULL DEFAULT 'system',
    CONSTRAINT uq_orders_categories_name UNIQUE (name)
);

-- --- Child: addresses  -> customers (CASCADE) ----------------------------
CREATE TABLE orders.addresses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT       NOT NULL,
    street        VARCHAR(255) NOT NULL,
    city          VARCHAR(100) NOT NULL,
    state         VARCHAR(100),
    postal_code   VARCHAR(20),
    country       VARCHAR(100) NOT NULL,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    address_type  VARCHAR(32)  NOT NULL DEFAULT 'HOME',
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64)  NOT NULL DEFAULT 'system',
    updated_by    VARCHAR(64)  NOT NULL DEFAULT 'system',
    CONSTRAINT fk_orders_addresses_customer
        FOREIGN KEY (customer_id) REFERENCES orders.customers (id) ON DELETE CASCADE
);

-- --- Child: orders  -> customers (CASCADE), addresses x2 (SET NULL) ------
CREATE TABLE orders.orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT       NOT NULL,
    order_date           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status               VARCHAR(32)  NOT NULL,
    total_amount         NUMERIC(19,2) NOT NULL,
    shipping_address_id  BIGINT,
    billing_address_id   BIGINT,
    order_number         VARCHAR(40),
    version              BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(64)  NOT NULL DEFAULT 'system',
    updated_by           VARCHAR(64)  NOT NULL DEFAULT 'system',
    CONSTRAINT fk_orders_order_customer
        FOREIGN KEY (customer_id) REFERENCES orders.customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_orders_order_shipping_address
        FOREIGN KEY (shipping_address_id) REFERENCES orders.addresses (id) ON DELETE SET NULL,
    CONSTRAINT fk_orders_order_billing_address
        FOREIGN KEY (billing_address_id) REFERENCES orders.addresses (id) ON DELETE SET NULL,
    CONSTRAINT ck_orders_order_status
        CHECK (status IN ('PLACED', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_order_total_non_negative CHECK (total_amount >= 0)
);

-- --- Child: order_items  -> orders (CASCADE), products (RESTRICT) --------
CREATE TABLE orders.order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT        NOT NULL,
    product_id   BIGINT        NOT NULL,
    quantity     INTEGER       NOT NULL,
    unit_price   NUMERIC(19,2) NOT NULL,
    total_price  NUMERIC(19,2) NOT NULL,
    version      BIGINT        NOT NULL DEFAULT 0,
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(64)   NOT NULL DEFAULT 'system',
    updated_by   VARCHAR(64)   NOT NULL DEFAULT 'system',
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)
        REFERENCES orders.orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
        REFERENCES orders.products (id) ON DELETE RESTRICT,
    CONSTRAINT ck_order_items_quantity_positive   CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_non_neg  CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_total_non_negative  CHECK (total_price >= 0)
);

-- --- Join: product_categories (many-to-many) ------------------------------
CREATE TABLE orders.product_categories (
    product_id   BIGINT NOT NULL,
    category_id  BIGINT NOT NULL,
    version      BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_orders_product_categories PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_orders_pc_product  FOREIGN KEY (product_id)
        REFERENCES orders.products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_pc_category FOREIGN KEY (category_id)
        REFERENCES orders.categories (id) ON DELETE RESTRICT
);

-- --- Child: payments  -> orders (1:1, CASCADE) ---------------------------
CREATE TABLE orders.payments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT        NOT NULL,
    amount           NUMERIC(19,2) NOT NULL,
    payment_method   VARCHAR(32)   NOT NULL,
    status           VARCHAR(32)   NOT NULL,
    transaction_id   VARCHAR(255),
    payment_date     TIMESTAMP,
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64)   NOT NULL DEFAULT 'system',
    updated_by       VARCHAR(64)   NOT NULL DEFAULT 'system',
    CONSTRAINT uq_payments_order_id UNIQUE (order_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id)
        REFERENCES orders.orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_payments_amount_non_negative CHECK (amount >= 0)
);

-- --- Event store (append-only, event sourcing) ----------------------------
CREATE TABLE orders.event_store (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    UUID         NOT NULL,
    aggregate_type  VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    version         INTEGER      NOT NULL,
    occurred_at     TIMESTAMP    NOT NULL,
    payload         TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_event_store_aggregate_version UNIQUE (aggregate_id, version)
);

-- --- Idempotency keys (order write retries) ------------------------------
CREATE TABLE orders.idempotency_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64)  NOT NULL,
    http_method     VARCHAR(10)  NOT NULL,
    request_path    VARCHAR(255) NOT NULL,
    response_status INTEGER      NOT NULL,
    response_body   TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_idempotency_key UNIQUE (idempotency_key)
);

-- --- Audit log (GDPR compliance trail) -----------------------------------
CREATE TABLE orders.audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT       NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    actor       VARCHAR(255) NOT NULL,
    detail      TEXT,
    occurred_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --- Transactional outbox (Kafka publishing) ------------------------------
CREATE TABLE orders.outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    event_type     VARCHAR(64)  NOT NULL,
    payload        TEXT         NOT NULL,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts       INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at   TIMESTAMP
);

-- --- Orders schema indexes -----------------------------------------------
CREATE INDEX idx_orders_addresses_customer_id    ON orders.addresses (customer_id);
CREATE INDEX idx_orders_orders_customer_id       ON orders.orders (customer_id);
CREATE INDEX idx_orders_orders_shipping_addr_id  ON orders.orders (shipping_address_id);
CREATE INDEX idx_orders_orders_billing_addr_id   ON orders.orders (billing_address_id);
CREATE INDEX idx_orders_order_items_order_id     ON orders.order_items (order_id);
CREATE INDEX idx_orders_order_items_product_id   ON orders.order_items (product_id);
CREATE INDEX idx_orders_pc_category_id           ON orders.product_categories (category_id);
CREATE UNIQUE INDEX uq_orders_orders_order_number ON orders.orders (order_number);
CREATE INDEX idx_orders_event_store_aggregate_id ON orders.event_store (aggregate_id);
CREATE INDEX idx_orders_audit_log_customer_id    ON orders.audit_log (customer_id);
CREATE INDEX idx_orders_outbox_status_id         ON orders.outbox (status, id);

-- =============================================================================
-- SCHEMA: admin  —  Managed by admin-service (port 8085)
-- =============================================================================
-- Managed by Liquibase in admin-service
CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE admin.dashboard_snapshots (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name   VARCHAR(128)   NOT NULL,
    metric_value  NUMERIC(19, 2) NOT NULL,
    recorded_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE admin.audit_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR(64)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    action        VARCHAR(64)  NOT NULL,
    performed_by  VARCHAR(255) NOT NULL,
    performed_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    details       JSONB,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE admin.idempotency_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64)  NOT NULL,
    response_status INTEGER      NOT NULL,
    response_body   TEXT         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_admin_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX idx_admin_audit_entries_entity      ON admin.audit_entries (entity_type, entity_id);
CREATE INDEX idx_admin_audit_entries_performed_by ON admin.audit_entries (performed_by);
CREATE INDEX idx_admin_dashboard_snapshots_metric ON admin.dashboard_snapshots (metric_name);

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
